Added more test cases for TTL for Zero TTL and Created test cases for…
wso2/wso2-qa-artifacts pull request #104
Opened 2016-09-07 11:28 UTC by pubudup

… topics. Updated README.me with test cases

2017-06-29 09:53 UTC, nu1silva reviewed
what are the uses of the following?
- mbtestcases.properties
- mbtestcases.xml
- module_mbtestcases.xml

I can build the project without them it seems.

2017-06-29 09:55 UTC, nu1silva requested changes
Check the other comments and if not required remove the files.

2017-06-29 11:17 UTC, pubudup commented
Looks like these files were created with the idea project. I have removed these since it is not required to build the project after testing it.

2017-06-29 11:20 UTC, nu1silva approved these changes

2017-06-29 11:20 UTC, merged

2018-01-13 03:34 UTC, dakshika reviewed
License missing
Needs to clean up unwanted spaces
Add Doc comments

2018-01-13 03:34 UTC, dakshika commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/DurableTopic/DurableTopicReceive.java
> +
Missing license headers

2018-01-13 03:34 UTC, dakshika commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/DurableTopic/DurableTopicReceive.java
> +        // queueSession.close();
cleanup file

2018-01-13 03:34 UTC, dakshika commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/DurableTopic/DurableTopicSend.java
> +
Add license headers

2018-01-13 03:34 UTC, dakshika commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/DurableTopic/DurableTopicSend.java
> +
Clean up unwanted spaces

2018-01-13 03:34 UTC, dakshika commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/Queues/DifferentTTLSend.java
> +
Add License

2018-01-13 03:34 UTC, dakshika commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/Queues/DifferentTTLSend.java
> +/**
Provide proper class description

2018-01-13 03:34 UTC, dakshika commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/Queues/DifferentTTLSend.java
> +
clean up space

2018-01-13 03:34 UTC, dakshika commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/Queues/DifferentTTLSend.java
> +
clean up unwanted spaces

2018-01-13 03:34 UTC, dakshika commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/Queues/QueueReceiveDefault.java
> +
Missing License headers

2018-01-13 03:34 UTC, dakshika commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/Queues/QueueReceiveDefault.java
> +
Missing Doc comments

2018-01-13 03:34 UTC, dakshika commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/Queues/QueueSendDefault.java
> +
License missing

2018-01-16 17:08 UTC, ruwany reviewed
Better to run through the files, once more and fix these issues wherever necessary.

2018-01-16 17:08 UTC, ruwany commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/Queues/QueueReceiveDefault.java
> +    public static final String QPID_ICF = "org.wso2.andes.jndi.PropertiesFileInitialContextFactory";
Can we not use a constant file and retrieve these from one place. Configs seem to be repeated.

2018-01-16 17:08 UTC, ruwany commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/RedeliveryDelayWithTTL/Queues/ReceiveFromQueue.java
> +package ttl.RedeliveryDelayWithTTL.Queues;
Missing license.

2018-01-16 17:08 UTC, ruwany commented on products/wso2_MB/combined_scenarios/MBTestCases/src/main/java/ttl/RedeliveryDelayWithTTL/Queues/ReceiveFromQueue.java
> +
Formatting issues?

2018-01-17 07:23 UTC, pubudup commented
@dakshika @ruwany @ushanib : I have incorporated requested changes and sent a new pull request here: https://github.com/wso2/wso2-qa-artifacts/pull/127