added json sample with null values.
wso2/wso2-qa-artifacts pull request #82
Opened 2016-05-03 07:00 UTC by chaminda

Please review and merg.

2016-05-03 10:57 UTC, ushanib commented
Hi Chaminda,

Please include a read me file with the necessary information.

Thanks
Ushani

2016-05-03 12:51 UTC, chaminda commented
Added README.md please review and merge.

2017-06-29 09:42 UTC, nu1silva requested changes

2017-06-29 09:42 UTC, nu1silva commented on products/wso2_ESB/product_features/features/transports/vfs/vfs_smb/StockQuoteProxy.xml
> +               <address uri="vfs:file:///home/chaminda/Documents/Testing/ESB/5.0.0/runtime/beta2/vfs/out"/>
Can we add instructions to the README where these values should change

2017-06-29 09:42 UTC, nu1silva commented on products/wso2_ESB/product_features/features/transports/vfs/vfs_smb/StockQuoteProxyEncrypted.xml
> +               <address uri="vfs:file:///home/chaminda/Documents/Testing/ESB/5.0.0/runtime/beta2/vfs/out"/>
Add to README to change path

2017-06-30 05:37 UTC, nu1silva approved these changes

2017-06-30 05:38 UTC, merged